name: "bluebell"
mode: "dev"
port: 8081
start_time: "2022-01-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "rm-2ze4kp1x07f9638t9uo.mysql.rds.aliyuncs.com"
  port: 3306
  user: "root"
  password: "zhaoBIN138"
  db_name: "bluebell"
  max_conns: 200
  max_idle_conns: 50

redis:
  host: "101.200.241.73"
  port: 16379
  db: 0
  password: "ZHAOBIN138"
  pool_size: 100